name: Swift

on:
  push:
    branches:  [ main, develop ] 
    paths:
      - cli/**
  pull_request:
    branches: [ main, develop ]
    paths:
      - cli/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: "**/.build"
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
    - uses: fwal/setup-swift@v1
    - name: Build
      run: swift build -c release
    - name: Run tests
      run: swift test -c release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: generator-binary
          path: cli/.build/release/changelog-generator
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    if:  ${{ github.ref == 'refs/heads/main' }}
    defaults:
      run:
        working-directory: cli
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path:  "**/.build"
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: generator-binary
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.6.1
      with:
          context: cli
          push: true
          tags: drallgood/changelog-generator:latest,drallgood/changelog-generator:${{ github.sha }}
    - name: Update repo description
      uses: peter-evans/dockerhub-description@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: drallgood/changelog-generator
